### ISSUE TITLE
ui/toggle-button forces background to be gray on :hover

### ISSUE THREAD

**Issue by aadsm** [montagejs/montage#960]
``` javascript
"toggle": {
    "prototype": "montage/ui/toggle-button.reel",
    "properties": {
      "label": "off",
      "pressedLabel": "on",
      "pressedClass": "pressed",
      "element": {"#": "toggle"}
    }
  }
}
```

``` css
.toggle.pressed {
  background-color: red;
}

.toggle {
  background-color: green;
}
```
